name: destroy
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  WORKLOAD_WORKING_DIRECTORY: iac/workload
  WORKLOAD_REMOTE_STATE_KEY: synapse.terraform.tfstate
  REMOTE_STATE_RG: synapse-demo-centralus
  REMOTE_STATE_SA: tfsynapsecd
  REMOTE_STATE_CONTAINER: synapse-remote-state-centralus-demo
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  destroy-workload:
    name: 'destroy workload'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKLOAD_WORKING_DIRECTORY }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
      - name: 'Get Deployer Secrets'
        id: get-deployer-secret
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.DEPLOYER_KEY_VAULT }}
          secrets: 'synapse-demo-centralus-deployer, tfsynapsecd-access-key'
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
      - name: 'Terraform Init'
        env: 
          TF_CLI_ARGS_init: "-backend-config='resource_group_name=${{env.REMOTE_STATE_RG}}' -backend-config='storage_account_name=${{env.REMOTE_STATE_SA}}' -backend-config='container_name=${{env.REMOTE_STATE_CONTAINER}}' -backend-config='key=${{env.WORKLOAD_REMOTE_STATE_KEY}}'"
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfsynapsecd-access-key }}
        run: terraform init
      - name: 'Terraform Validate'
        run: terraform validate
      - name: 'Terraform Destroy'
        env:        
          ARM_CLIENT_SECRET: ${{ steps.get-deployer-secret.outputs.synapse-demo-centralus-deployer}}
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfsynapsecd-access-key }}
        run: terraform destroy -auto-approve